Geometric Lift from \(S^1\) to \(S^2\): Residual Efolding and the Emergence of Comoving Topology on the Two-Sphere

The continuous Arcan(\(\tau\)) family, once reduced through residual efolding, organises a dense equidistributed orbit on the unit circle \(S^1\). The same residual structure admits a natural geometric lift to the two-sphere \(S^2\). This lift is not an arbitrary embedding; it is the unique polar realisation that preserves both the radial temperature schedule of the Cosmological Clock and the residual angular memory generated by the Arcan(\(\tau\)) cascade.

On the unit sphere the residual efolding is realised by the standard polar embedding

\[
\begin{align*}
\theta(\lambda)&=\pi\lambda,\\
\phi(\lambda)&=\phi_{\rm wind}(\lambda,n)=2\pi(1-\lambda)+n\delta,
\end{align*}
\]

where \(\lambda\in[0,1]\) parametrises normalised progress through a single residual cycle and \(n\in\mathbb{Z}\) indexes successive cycles. The polar angle \(\theta\) inherits the radial coordinate of the Cosmological Clock: as \(\lambda\) advances from 0 to 1 the system cools continuously from the North Pole (\(\theta=0\)) to the South Pole (\(\theta=\pi\)). Simultaneously the azimuthal coordinate \(\phi_{\rm wind}\) carries the residual winding. The term \(2\pi(1-\lambda)\) supplies the primary adiabatic turn, while the additive offset \(n\delta\) accumulates the residual seed

\[
\delta=7\psi-\frac{\pi}{3}\approx0.0051676144
\]

generated by seven consecutive multiples of the angular bridge \(\psi\).

Because \(\phi\) is defined only modulo \(2\pi\), the completion of any full azimuthal turn forces the instantaneous identification

\[
\phi_{\rm wind}(1,n)\equiv0\pmod{2\pi}.
\]

On the geometry of \(S^2\) this identification appears as an instantaneous transport of the winding coordinate back to the origin of the azimuthal circle. At the same instant the radial (temperature) coordinate, having reached the South Pole, jumps discontinuously from near-zero back to the Arcan maximum \(2\pi\). The resulting dynamical picture is therefore a continuous adiabatic orbital cooling followed by a 360° spherical recycle—precisely the residual efolding of the Cosmological Clock lifted from the circle to the two-sphere.

The topology that emerges is comoving. Every successive cycle remains phase-locked to the discrete-tick lattice \(\varepsilon=10^{-9}\). The residual offset \(n\delta\) is never erased; it is transported forward as a persistent angular memory. Consequently the entire orbital flow on \(S^2\) advances in lock-step with the macroscopic scale factor \(a(N)=\mathrm{e}^{\varepsilon N}\). The polar chart

\[
x=\sin\theta\cos\phi,\qquad
y=\sin\theta\sin\phi,\qquad
z=\cos\theta
\]

is the coordinate expression of this emerging geometry. It converts the abstract residual cascade into a concrete adiabatic spiral whose successive turns differ only by the accumulated residual \(\delta\).

In this way the geometric lift from \(S^1\) to \(S^2\) completes the narrative begun on the circle. The same residual that renders the orbit on \(S^1\) dense and equidistributed now organises a continuous, recyclable, comoving flow on the two-sphere. The construction is closed: the continuous Arcan(\(\tau\)) family generates the residual, the residual generates the efolding, and the efolding lifts without remainder from the one-sphere to the two-sphere while remaining phase-locked to the Cosmological Clock.
